---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chamo-demo-pv-volume
  labels:
    type: local
spec:
  storageClassName: chamo-demo-storageclass
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
