apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chamo-demo-filestore-pvc
spec:
  storageClassName: ""
  volumeName: chamo-demo-pv-filestore
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100G
