---
apiVersion: v1
kind: Pod
metadata:
  name: chamo-demo-pod
spec:
  containers:
    - name: chamo-demo-pod
      image: debian
      command: [ "sleep" ]
      args: [ "infinity" ]
      env:
        - name: CLOUD_1
          valueFrom:
            configMapKeyRef:
              name: chamo-demo-configmap
              key: cloud_1
        - name: CLOUD_2
          valueFrom:
            configMapKeyRef:
              name: chamo-demo-configmap
              key: cloud_2
        - name: CLOUD_3
          valueFrom:
            configMapKeyRef:
              name: chamo-demo-configmap
              key: cloud_3
      envFrom:  
      - secretRef:
           name: chamo-demo-secrets

