---
apiVersion: v1
kind: Service
metadata:
  name: chamo-demo-service-statefulset
  labels:
    name: chamo-demo-service-statefulset
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    name: nginx
