# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#container-v1-core
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#pod-v1-core
---
apiVersion: v1
kind: Pod
metadata:
  name: chamo-demo
  labels:
    name: webserver
spec:
  containers:
  - name: webserver
    image: nginx
